/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hurri
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SearchBar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ShoppingCart = new javax.swing.JLabel();
        ProfileIcon = new javax.swing.JLabel();
        NavBar = new javax.swing.JPanel();
        Electrobyte = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Orders = new javax.swing.JTextField();
        Products = new javax.swing.JTextField();
        Dashboard = new javax.swing.JTextField();
        Reviews = new javax.swing.JTextField();
        Users = new javax.swing.JTextField();
        LogoutBtn = new javax.swing.JButton();
        TodaysOrders = new javax.swing.JPanel();
        TodaysNoOfOrders = new javax.swing.JTextField();
        TotalSales = new javax.swing.JPanel();
        totalSales = new javax.swing.JTextField();
        TotalRevenue = new javax.swing.JPanel();
        totalRevenue = new javax.swing.JTextField();
        TotalSales1 = new javax.swing.JPanel();
        lowStocks = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchBar.setText("Search");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/resized search.png"))); // NOI18N

        ShoppingCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-shopping-cart-30.png"))); // NOI18N
        ShoppingCart.setText("jLabel2");

        ProfileIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-male-user-24.png"))); // NOI18N

        NavBar.setBackground(new java.awt.Color(153, 153, 153));

        Electrobyte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Electrobyte.setText("Electrobyte");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Electrobyte (Custom) (Custom) (1).png"))); // NOI18N

        Orders.setBackground(new java.awt.Color(153, 153, 153));
        Orders.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Orders.setText("            Orders");
        Orders.setAlignmentX(1.0F);
        Orders.setAlignmentY(1.0F);
        Orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersActionPerformed(evt);
            }
        });

        Products.setBackground(new java.awt.Color(153, 153, 153));
        Products.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Products.setText("           Products");
        Products.setAlignmentX(1.0F);
        Products.setAlignmentY(1.0F);
        Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductsActionPerformed(evt);
            }
        });

        Dashboard.setBackground(new java.awt.Color(204, 204, 204));
        Dashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Dashboard.setText("         Dashboard");
        Dashboard.setAlignmentX(1.0F);
        Dashboard.setAlignmentY(1.0F);
        Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardActionPerformed(evt);
            }
        });

        Reviews.setBackground(new java.awt.Color(153, 153, 153));
        Reviews.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Reviews.setText("           Reviews");
        Reviews.setAlignmentX(1.0F);
        Reviews.setAlignmentY(1.0F);
        Reviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewsActionPerformed(evt);
            }
        });

        Users.setBackground(new java.awt.Color(153, 153, 153));
        Users.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Users.setText("             Users");
        Users.setAlignmentX(1.0F);
        Users.setAlignmentY(1.0F);
        Users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersActionPerformed(evt);
            }
        });

        LogoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Orders, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Products)
            .addComponent(Reviews, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Electrobyte)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(Users, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(34, 34, 34))
            .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Electrobyte))
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(112, 112, 112)
                .addComponent(Orders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Products, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Reviews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(41, 41, 41))
            .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(NavBarLayout.createSequentialGroup()
                    .addGap(98, 98, 98)
                    .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(414, Short.MAX_VALUE)))
        );

        TodaysOrders.setBackground(new java.awt.Color(204, 204, 255));

        TodaysNoOfOrders.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TodaysNoOfOrders.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TodaysNoOfOrders.setText("Today's No. of Orders");
        TodaysNoOfOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodaysNoOfOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TodaysOrdersLayout = new javax.swing.GroupLayout(TodaysOrders);
        TodaysOrders.setLayout(TodaysOrdersLayout);
        TodaysOrdersLayout.setHorizontalGroup(
            TodaysOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TodaysOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TodaysNoOfOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        TodaysOrdersLayout.setVerticalGroup(
            TodaysOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TodaysOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TodaysNoOfOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalSales.setBackground(new java.awt.Color(204, 204, 255));

        totalSales.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalSales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalSales.setText("Total Sales $");
        totalSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalSalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TotalSalesLayout = new javax.swing.GroupLayout(TotalSales);
        TotalSales.setLayout(TotalSalesLayout);
        TotalSalesLayout.setHorizontalGroup(
            TotalSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalSales, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        TotalSalesLayout.setVerticalGroup(
            TotalSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        TotalRevenue.setBackground(new java.awt.Color(204, 204, 255));

        totalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalRevenue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalRevenue.setText("Total Revenue $");
        totalRevenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalRevenueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TotalRevenueLayout = new javax.swing.GroupLayout(TotalRevenue);
        TotalRevenue.setLayout(TotalRevenueLayout);
        TotalRevenueLayout.setHorizontalGroup(
            TotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalRevenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        TotalRevenueLayout.setVerticalGroup(
            TotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalRevenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        TotalSales1.setBackground(new java.awt.Color(204, 204, 255));

        lowStocks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lowStocks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lowStocks.setText("Low Stocks");
        lowStocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowStocksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TotalSales1Layout = new javax.swing.GroupLayout(TotalSales1);
        TotalSales1.setLayout(TotalSales1Layout);
        TotalSales1Layout.setHorizontalGroup(
            TotalSales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalSales1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lowStocks, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );
        TotalSales1Layout.setVerticalGroup(
            TotalSales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalSales1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lowStocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(TodaysOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(TotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(ProfileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(TotalSales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ShoppingCart, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ProfileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TodaysOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addComponent(TotalSales1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersActionPerformed

    private void ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductsActionPerformed

    private void DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardActionPerformed

    private void ReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReviewsActionPerformed

    private void UsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsersActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void TodaysNoOfOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodaysNoOfOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TodaysNoOfOrdersActionPerformed

    private void totalSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalSalesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalSalesActionPerformed

    private void totalRevenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalRevenueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalRevenueActionPerformed

    private void lowStocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowStocksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lowStocksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Dashboard;
    private javax.swing.JLabel Electrobyte;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel NavBar;
    private javax.swing.JTextField Orders;
    private javax.swing.JTextField Products;
    private javax.swing.JLabel ProfileIcon;
    private javax.swing.JTextField Reviews;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JLabel ShoppingCart;
    private javax.swing.JTextField TodaysNoOfOrders;
    private javax.swing.JPanel TodaysOrders;
    private javax.swing.JPanel TotalRevenue;
    private javax.swing.JPanel TotalSales;
    private javax.swing.JPanel TotalSales1;
    private javax.swing.JTextField Users;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lowStocks;
    private javax.swing.JTextField totalRevenue;
    private javax.swing.JTextField totalSales;
    // End of variables declaration//GEN-END:variables
}
