/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hurri
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SearchBar = new javax.swing.JTextField();
        NavBar = new javax.swing.JPanel();
        Electrobyte = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        usersBTN = new javax.swing.JButton();
        dashboardBTN = new javax.swing.JButton();
        ordersBTN = new javax.swing.JButton();
        productsBTN = new javax.swing.JButton();
        reviewBTN = new javax.swing.JButton();
        TodaysOrders = new javax.swing.JPanel();
        TodaysNoOfOrders = new javax.swing.JTextField();
        TotalSales = new javax.swing.JPanel();
        totalSales = new javax.swing.JTextField();
        TotalRevenue = new javax.swing.JPanel();
        totalRevenue = new javax.swing.JTextField();
        TotalSales1 = new javax.swing.JPanel();
        lowStocks = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchBar.setText("Search");

        NavBar.setBackground(new java.awt.Color(153, 153, 153));

        Electrobyte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Electrobyte.setText("Electrobyte");

        Logo.setBackground(new java.awt.Color(0, 0, 0));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Electrobyte (Custom) (Custom) (1).png"))); // NOI18N

        LogoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setText("Logout");

        usersBTN.setBackground(new java.awt.Color(153, 153, 153));
        usersBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usersBTN.setText("Users");
        usersBTN.setBorder(null);

        dashboardBTN.setBackground(new java.awt.Color(153, 153, 153));
        dashboardBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboardBTN.setText("Dashboard");
        dashboardBTN.setBorder(null);

        ordersBTN.setBackground(new java.awt.Color(153, 153, 153));
        ordersBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ordersBTN.setText("Orders");
        ordersBTN.setBorder(null);

        productsBTN.setBackground(new java.awt.Color(153, 153, 153));
        productsBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productsBTN.setText("Products");
        productsBTN.setBorder(null);

        reviewBTN.setBackground(new java.awt.Color(153, 153, 153));
        reviewBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reviewBTN.setText("Reviews");
        reviewBTN.setBorder(null);

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(34, 34, 34))
            .addComponent(usersBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboardBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ordersBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productsBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Electrobyte)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(reviewBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Electrobyte))
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(dashboardBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(usersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ordersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(productsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(reviewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(41, 41, 41))
        );

        TodaysOrders.setBackground(new java.awt.Color(204, 204, 255));

        TodaysNoOfOrders.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TodaysNoOfOrders.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TodaysNoOfOrders.setText("Today's No. of Orders");

        javax.swing.GroupLayout TodaysOrdersLayout = new javax.swing.GroupLayout(TodaysOrders);
        TodaysOrders.setLayout(TodaysOrdersLayout);
        TodaysOrdersLayout.setHorizontalGroup(
            TodaysOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TodaysOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TodaysNoOfOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        TodaysOrdersLayout.setVerticalGroup(
            TodaysOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TodaysOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TodaysNoOfOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalSales.setBackground(new java.awt.Color(204, 204, 255));

        totalSales.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalSales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalSales.setText("Total Sales $");

        javax.swing.GroupLayout TotalSalesLayout = new javax.swing.GroupLayout(TotalSales);
        TotalSales.setLayout(TotalSalesLayout);
        TotalSalesLayout.setHorizontalGroup(
            TotalSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalSales, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        TotalSalesLayout.setVerticalGroup(
            TotalSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        TotalRevenue.setBackground(new java.awt.Color(204, 204, 255));

        totalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalRevenue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalRevenue.setText("Total Revenue $");

        javax.swing.GroupLayout TotalRevenueLayout = new javax.swing.GroupLayout(TotalRevenue);
        TotalRevenue.setLayout(TotalRevenueLayout);
        TotalRevenueLayout.setHorizontalGroup(
            TotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalRevenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        TotalRevenueLayout.setVerticalGroup(
            TotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalRevenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        TotalSales1.setBackground(new java.awt.Color(204, 204, 255));

        lowStocks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lowStocks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lowStocks.setText("Low Stocks");

        javax.swing.GroupLayout TotalSales1Layout = new javax.swing.GroupLayout(TotalSales1);
        TotalSales1.setLayout(TotalSales1Layout);
        TotalSales1Layout.setHorizontalGroup(
            TotalSales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalSales1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lowStocks, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );
        TotalSales1Layout.setVerticalGroup(
            TotalSales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalSales1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lowStocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(TodaysOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(TotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addComponent(TotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(TotalSales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(NavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TodaysOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addComponent(TotalSales1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(44, 44, 44)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Electrobyte;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel NavBar;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JTextField TodaysNoOfOrders;
    private javax.swing.JPanel TodaysOrders;
    private javax.swing.JPanel TotalRevenue;
    private javax.swing.JPanel TotalSales;
    private javax.swing.JPanel TotalSales1;
    private javax.swing.JButton dashboardBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lowStocks;
    private javax.swing.JButton ordersBTN;
    private javax.swing.JButton productsBTN;
    private javax.swing.JButton reviewBTN;
    private javax.swing.JTextField totalRevenue;
    private javax.swing.JTextField totalSales;
    private javax.swing.JButton usersBTN;
    // End of variables declaration//GEN-END:variables
}
