/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import dao.UserTableDao;
import dao.ProductDao;
import dao.OrderDao;
import dao.UserDao;
import model.User;
import view.Login;
import view.UserTable;
import view.ItemsPage;
import view.AddProduct;
import controller.*;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hurri
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        loadLowStockTable();
        setTodaysOrderCount();
        setTotalSales();
        setTotalActiveUsers();
    }
    Login login = new Login();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NavBar = new javax.swing.JPanel();
        Electrobyte = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        usersBTN = new javax.swing.JButton();
        dashboardBTN = new javax.swing.JButton();
        ordersBTN = new javax.swing.JButton();
        productsBTN = new javax.swing.JButton();
        reviewBTN = new javax.swing.JButton();
        TodaysOrders = new javax.swing.JPanel();
        TodaysNoOfOrders = new javax.swing.JTextField();
        NumOrder = new javax.swing.JLabel();
        TotalSales = new javax.swing.JPanel();
        totalSales = new javax.swing.JTextField();
        Sales = new javax.swing.JLabel();
        TotalRevenue = new javax.swing.JPanel();
        totalRevenue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TotalSales1 = new javax.swing.JPanel();
        lowStocks = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        StockTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NavBar.setBackground(new java.awt.Color(153, 153, 153));

        Electrobyte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Electrobyte.setText("Electrobyte");

        Logo.setBackground(new java.awt.Color(0, 0, 0));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Electrobyte (Custom) (Custom) (1).png"))); // NOI18N

        LogoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        usersBTN.setBackground(new java.awt.Color(153, 153, 153));
        usersBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usersBTN.setText("Users");
        usersBTN.setBorder(null);
        usersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBTNActionPerformed(evt);
            }
        });

        dashboardBTN.setBackground(new java.awt.Color(153, 153, 153));
        dashboardBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboardBTN.setText("Dashboard");
        dashboardBTN.setBorder(null);
        dashboardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBTNActionPerformed(evt);
            }
        });

        ordersBTN.setBackground(new java.awt.Color(153, 153, 153));
        ordersBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ordersBTN.setText("Orders");
        ordersBTN.setBorder(null);
        ordersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersBTNActionPerformed(evt);
            }
        });

        productsBTN.setBackground(new java.awt.Color(153, 153, 153));
        productsBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productsBTN.setText("Products");
        productsBTN.setBorder(null);
        productsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsBTNActionPerformed(evt);
            }
        });

        reviewBTN.setBackground(new java.awt.Color(153, 153, 153));
        reviewBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reviewBTN.setText("Reviews");
        reviewBTN.setBorder(null);
        reviewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usersBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboardBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ordersBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productsBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reviewBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Electrobyte))
                    .addGroup(NavBarLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(LogoutBtn)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NavBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Electrobyte))
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(dashboardBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(usersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ordersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(productsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(reviewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(38, 38, 38))
        );

        TodaysOrders.setBackground(new java.awt.Color(204, 204, 255));

        TodaysNoOfOrders.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TodaysNoOfOrders.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TodaysNoOfOrders.setText("Today's No. of Orders");

        NumOrder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        NumOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NumOrder.setText("0");

        javax.swing.GroupLayout TodaysOrdersLayout = new javax.swing.GroupLayout(TodaysOrders);
        TodaysOrders.setLayout(TodaysOrdersLayout);
        TodaysOrdersLayout.setHorizontalGroup(
            TodaysOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TodaysOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TodaysNoOfOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TodaysOrdersLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(NumOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TodaysOrdersLayout.setVerticalGroup(
            TodaysOrdersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TodaysOrdersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TodaysNoOfOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(NumOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        TotalSales.setBackground(new java.awt.Color(204, 204, 255));

        totalSales.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalSales.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalSales.setText("Total Sales $");

        Sales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Sales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Sales.setText("MONEY");

        javax.swing.GroupLayout TotalSalesLayout = new javax.swing.GroupLayout(TotalSales);
        TotalSales.setLayout(TotalSalesLayout);
        TotalSalesLayout.setHorizontalGroup(
            TotalSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalSales, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TotalSalesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TotalSalesLayout.setVerticalGroup(
            TotalSalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalSalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(Sales, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalRevenue.setBackground(new java.awt.Color(204, 204, 255));

        totalRevenue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        totalRevenue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalRevenue.setText("Total Active Users");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("0");

        javax.swing.GroupLayout TotalRevenueLayout = new javax.swing.GroupLayout(TotalRevenue);
        TotalRevenue.setLayout(TotalRevenueLayout);
        TotalRevenueLayout.setHorizontalGroup(
            TotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalRevenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(TotalRevenueLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TotalRevenueLayout.setVerticalGroup(
            TotalRevenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalRevenueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalSales1.setBackground(new java.awt.Color(204, 204, 255));

        lowStocks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lowStocks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lowStocks.setText("Low Stocks");

        StockTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        StockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PId", "ProductName", "Quantity", "Category"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        StockTable.setRowHeight(40);
        StockTable.setRowMargin(20);
        jScrollPane2.setViewportView(StockTable);
        if (StockTable.getColumnModel().getColumnCount() > 0) {
            StockTable.getColumnModel().getColumn(0).setResizable(false);
            StockTable.getColumnModel().getColumn(0).setPreferredWidth(10);
            StockTable.getColumnModel().getColumn(1).setResizable(false);
            StockTable.getColumnModel().getColumn(1).setPreferredWidth(30);
            StockTable.getColumnModel().getColumn(2).setResizable(false);
            StockTable.getColumnModel().getColumn(2).setPreferredWidth(30);
            StockTable.getColumnModel().getColumn(3).setResizable(false);
            StockTable.getColumnModel().getColumn(3).setPreferredWidth(30);
        }

        javax.swing.GroupLayout TotalSales1Layout = new javax.swing.GroupLayout(TotalSales1);
        TotalSales1.setLayout(TotalSales1Layout);
        TotalSales1Layout.setHorizontalGroup(
            TotalSales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalSales1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TotalSales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lowStocks, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        TotalSales1Layout.setVerticalGroup(
            TotalSales1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalSales1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lowStocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TodaysOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(TotalSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(TotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TotalSales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TotalRevenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalSales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TodaysOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TotalSales1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
    Login login = new Login();
    // login.setVisible(true);
    LoginController controller = new LoginController(login);
    controller.open();
    login.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_LogoutBtnActionPerformed

    private void usersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBTNActionPerformed
        UserTable userTable = new UserTable();
        UserTableController controller = new UserTableController(userTable, login);
        controller.loadUsers();
        controller.showUserTable();
        userTable.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_usersBTNActionPerformed

    private void productsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBTNActionPerformed
        ItemsPage itemsPage = new ItemsPage();
        ProductController.attachAddProductToItemsPage(itemsPage);
        itemsPage.setVisible(true);
        itemsPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_productsBTNActionPerformed

    private void dashboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBTNActionPerformed
    AdminDashboard dashboard = new AdminDashboard();
    dashboard.setVisible(true);
    dashboard.setLocationRelativeTo(null);
    this.dispose();
}//GEN-LAST:event_dashboardBTNActionPerformed

    private void ordersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBTNActionPerformed
        CustomersOrders ordersPage = new CustomersOrders();
        ordersPage.setVisible(true);
        ordersPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ordersBTNActionPerformed

    private void reviewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewBTNActionPerformed
     Review reviewsPage = new Review();
     reviewsPage.setVisible(true);
     reviewsPage.setLocationRelativeTo(null);
     this.dispose();
    }//GEN-LAST:event_reviewBTNActionPerformed

    private void loadLowStockTable() {
    String[] columns = {"PId", "ProductName", "Quantity", "Category"};
    DefaultTableModel model = new DefaultTableModel(columns, 0);

    ProductDao productDao = new ProductDao();
    List<Object[]> lowStockProducts = productDao.getLowStockProducts(5); // threshold = 5

    for (Object[] row : lowStockProducts) {
        model.addRow(row);
    }
    StockTable.setModel(model);
}

private void setTodaysOrderCount() {
    OrderDao orderDao = new OrderDao();
    int count = orderDao.getTodaysOrderCount();
    NumOrder.setText(String.valueOf(count));
}

private void setTotalActiveUsers() {
    UserDao userDao = new UserDao();
    int users = userDao.getTotalActiveUsers();
    jLabel1.setText(String.valueOf(users));
}

private void setTotalSales() {
    OrderDao orderDao = new OrderDao();
    double sales = orderDao.getTotalSales();
    Sales.setText(String.format("RS%.2f", sales)); // Shows as 12345.67
}

/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Electrobyte;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel NavBar;
    private javax.swing.JLabel NumOrder;
    private javax.swing.JLabel Sales;
    private javax.swing.JTable StockTable;
    private javax.swing.JTextField TodaysNoOfOrders;
    private javax.swing.JPanel TodaysOrders;
    private javax.swing.JPanel TotalRevenue;
    private javax.swing.JPanel TotalSales;
    private javax.swing.JPanel TotalSales1;
    private javax.swing.JButton dashboardBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lowStocks;
    private javax.swing.JButton ordersBTN;
    private javax.swing.JButton productsBTN;
    private javax.swing.JButton reviewBTN;
    private javax.swing.JTextField totalRevenue;
    private javax.swing.JTextField totalSales;
    private javax.swing.JButton usersBTN;
    // End of variables declaration//GEN-END:variables
}
