/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.OrderDao;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.TableRowSorter;
import controller.*;

/**
 *
 * @author NITRO V 15
 */
public class CustomersOrders extends javax.swing.JFrame {

    /**
     * Creates new form CustomerOrders
     */
    public CustomersOrders() {
        initComponents();
        
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>((DefaultTableModel) ReviewList.getModel());
        ReviewList.setRowSorter(rowSorter);

        jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                String text = jTextField1.getText();
                if (text.trim().length() == 0 || text.equals("Search")) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                }
            }
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                String text = jTextField1.getText();
                if (text.trim().length() == 0 || text.equals("Search")) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                }
            }
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                // Not needed for plain text fields
            }
        });
        
        loadOrderTable();
    }

    private void loadOrderTable() {
    String[] columns = {"P.Id", "Product Name", "CustomerName", "Date", "Price"};
    DefaultTableModel model = new DefaultTableModel(columns, 0);

    OrderDao orderDao = new OrderDao();
    List<Object[]> orderData = orderDao.getOrderTableData();
    for (Object[] row : orderData) {
        model.addRow(row);
    }
    ReviewList.setModel(model);
    // Enable search/filter
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>(model);
        ReviewList.setRowSorter(rowSorter);

        SearchBar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filter(rowSorter); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filter(rowSorter); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filter(rowSorter); }
            private void filter(TableRowSorter<DefaultTableModel> sorter) {
                String text = SearchBar.getText();
                if (text.trim().length() == 0 || text.equals("Search")) {
                    sorter.setRowFilter(null);
                } else {
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                }
            }
        });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReviewList = new javax.swing.JTable();
        SearchBar = new javax.swing.JTextField();
        NavBar = new javax.swing.JPanel();
        Electrobyte = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        usersBTN = new javax.swing.JButton();
        dashboardBTN = new javax.swing.JButton();
        ordersBTN = new javax.swing.JButton();
        productsBTN = new javax.swing.JButton();
        reviewBTN = new javax.swing.JButton();

        jButton4.setBackground(java.awt.Color.lightGray);
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton4.setText("User Management");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(java.awt.Color.lightGray);
        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton5.setText("Review");
        jButton5.setBorder(null);

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setText("Items");
        jButton3.setBorder(null);

        jButton2.setBackground(java.awt.Color.lightGray);
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton2.setText("Customer Orders");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 204));
        jButton1.setText("Overview");
        jButton1.setBorder(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("Order List");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        ReviewList.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ReviewList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "P.Id", "Product Name", "CustomerName", "Date", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReviewList.setRowHeight(40);
        ReviewList.setRowMargin(10);
        jScrollPane1.setViewportView(ReviewList);
        if (ReviewList.getColumnModel().getColumnCount() > 0) {
            ReviewList.getColumnModel().getColumn(0).setResizable(false);
            ReviewList.getColumnModel().getColumn(0).setPreferredWidth(1);
            ReviewList.getColumnModel().getColumn(1).setResizable(false);
            ReviewList.getColumnModel().getColumn(1).setPreferredWidth(200);
            ReviewList.getColumnModel().getColumn(2).setResizable(false);
            ReviewList.getColumnModel().getColumn(2).setPreferredWidth(160);
            ReviewList.getColumnModel().getColumn(3).setResizable(false);
            ReviewList.getColumnModel().getColumn(3).setPreferredWidth(60);
            ReviewList.getColumnModel().getColumn(4).setResizable(false);
            ReviewList.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        SearchBar.setText("Search");
        SearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchBarFocusLost(evt);
            }
        });

        NavBar.setBackground(new java.awt.Color(153, 153, 153));

        Electrobyte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Electrobyte.setText("Electrobyte");

        Logo.setBackground(new java.awt.Color(0, 0, 0));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Electrobyte (Custom) (Custom) (1).png"))); // NOI18N

        LogoutBtn.setBackground(new java.awt.Color(255, 51, 51));
        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setText("Logout");
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        usersBTN.setBackground(new java.awt.Color(153, 153, 153));
        usersBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usersBTN.setText("Users");
        usersBTN.setBorder(null);
        usersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBTNActionPerformed(evt);
            }
        });

        dashboardBTN.setBackground(new java.awt.Color(153, 153, 153));
        dashboardBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboardBTN.setText("Dashboard");
        dashboardBTN.setBorder(null);
        dashboardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBTNActionPerformed(evt);
            }
        });

        ordersBTN.setBackground(new java.awt.Color(153, 153, 153));
        ordersBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ordersBTN.setText("Orders");
        ordersBTN.setBorder(null);
        ordersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersBTNActionPerformed(evt);
            }
        });

        productsBTN.setBackground(new java.awt.Color(153, 153, 153));
        productsBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        productsBTN.setText("Products");
        productsBTN.setBorder(null);
        productsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productsBTNActionPerformed(evt);
            }
        });

        reviewBTN.setBackground(new java.awt.Color(153, 153, 153));
        reviewBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reviewBTN.setText("Reviews");
        reviewBTN.setBorder(null);
        reviewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavBarLayout = new javax.swing.GroupLayout(NavBar);
        NavBar.setLayout(NavBarLayout);
        NavBarLayout.setHorizontalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(usersBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboardBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ordersBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(productsBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reviewBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Electrobyte, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(LogoutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavBarLayout.setVerticalGroup(
            NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavBarLayout.createSequentialGroup()
                .addGroup(NavBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Logo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NavBarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Electrobyte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(58, 58, 58)
                .addComponent(dashboardBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(usersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ordersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(productsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(reviewBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 285, Short.MAX_VALUE)
                .addComponent(LogoutBtn)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(NavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(439, 439, 439)
                        .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Back button: Only this opens Overview and disposes this window
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        
        this.dispose();
    }

    // Overview button (jButton1)
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.dispose();
    }

    // Customer Orders button (jButton2)
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CustomersOrders ordersPage = new CustomersOrders();
        ordersPage.setVisible(true);
        ordersPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Items button (jButton3)
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        ItemsPage itemsPage = new ItemsPage();
        controller.ProductController.attachAddProductToItemsPage(itemsPage);
        itemsPage.setVisible(true);
        itemsPage.setLocationRelativeTo(null);
        this.dispose();
    }

    // User Management button (jButton4)
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        UserTable userTable = new UserTable();
        Login login = new Login();
        controller.UserTableController controller = new controller.UserTableController(userTable, login);
        controller.loadUsers();
        userTable.setVisible(true);
        userTable.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // ReviewsPage reviewsPage = new ReviewsPage();
        // reviewsPage.setVisible(true);
        // reviewsPage.setLocationRelativeTo(null);
        // this.dispose();
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusGained
      if (SearchBar.getText().equals("Search")) {
            SearchBar.setText("");
        }
    }//GEN-LAST:event_SearchBarFocusGained

    private void SearchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusLost
     if (SearchBar.getText().isEmpty()) {
            SearchBar.setText("Search");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarFocusLost

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        LoginController controller = new LoginController(login);
        controller.open();
        this.dispose();
    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void usersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBTNActionPerformed
        UserTable userTable = new UserTable();
        UserTableController controller = new UserTableController(userTable, new Login());
        controller.loadUsers();
        controller.showUserTable();
        userTable.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_usersBTNActionPerformed

    private void dashboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBTNActionPerformed
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_dashboardBTNActionPerformed

    private void ordersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBTNActionPerformed
        CustomersOrders ordersPage = new CustomersOrders();
        ordersPage.setVisible(true);
        ordersPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ordersBTNActionPerformed

    private void productsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productsBTNActionPerformed
        ItemsPage itemsPage = new ItemsPage();
        ProductController.attachAddProductToItemsPage(itemsPage);
        itemsPage.setVisible(true);
        itemsPage.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_productsBTNActionPerformed

    private void reviewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewBTNActionPerformed
         Review reviewsPage = new Review();
         reviewsPage.setVisible(true);
         reviewsPage.setLocationRelativeTo(null);
         this.dispose();
    }//GEN-LAST:event_reviewBTNActionPerformed

    private void overviewBtnActionPerformed(java.awt.event.ActionEvent evt) {
        AdminDashboard overview = new AdminDashboard();
        overview.setVisible(true);
        this.dispose();
    }

    private void userManageBtnActionPerformed(java.awt.event.ActionEvent evt) {
        UserTable userTable = new UserTable();
        Login login = new Login();
        controller.UserTableController controller = new controller.UserTableController(userTable, login);
        controller.loadUsers();
        userTable.setVisible(true);
        this.dispose();
    }

    private void itemsBtnActionPerformed(java.awt.event.ActionEvent evt) {
        ItemsPage itemsPage = new ItemsPage();
        controller.ProductController.attachAddProductToItemsPage(itemsPage);
        itemsPage.setVisible(true);
        this.dispose();
    }

    private void ordersBtnActionPerformed(java.awt.event.ActionEvent evt) {
        CustomersOrders orders = new CustomersOrders();
        orders.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(CustomersOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomersOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Electrobyte;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel NavBar;
    private javax.swing.JTable ReviewList;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton dashboardBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton ordersBTN;
    private javax.swing.JButton productsBTN;
    private javax.swing.JButton reviewBTN;
    private javax.swing.JButton usersBTN;
    // End of variables declaration//GEN-END:variables
}
