/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;


/**
 *
 * @author Himu
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        R_Username = new javax.swing.JTextField();
        R_Email = new javax.swing.JTextField();
        R_ResetBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        R_Security = new javax.swing.JPasswordField();
        R_Password = new javax.swing.JPasswordField();
        SecurityQue = new javax.swing.JLabel();
        showPassword = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(239, 239, 239));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Reset Password");

        jLabel3.setText("Username");

        jLabel5.setText("Password");

        jLabel6.setText("Email");

        R_Username.setBackground(new java.awt.Color(217, 217, 217));
        R_Username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                R_UsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                R_UsernameFocusLost(evt);
            }
        });
        R_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_UsernameActionPerformed(evt);
            }
        });

        R_Email.setBackground(new java.awt.Color(217, 217, 217));
        R_Email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                R_EmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                R_EmailFocusLost(evt);
            }
        });
        R_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_EmailActionPerformed(evt);
            }
        });

        R_ResetBtn.setBackground(new java.awt.Color(44, 132, 231));
        R_ResetBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        R_ResetBtn.setForeground(new java.awt.Color(255, 255, 255));
        R_ResetBtn.setText("Reset");
        R_ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R_ResetBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("One stop solution for all electronics");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Electrobyte");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Electrobyte (Custom) (Custom) (1).png"))); // NOI18N

        R_Security.setBackground(new java.awt.Color(217, 217, 217));
        R_Security.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                R_SecurityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                R_SecurityFocusLost(evt);
            }
        });

        R_Password.setBackground(new java.awt.Color(217, 217, 217));
        R_Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                R_PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                R_PasswordFocusLost(evt);
            }
        });

        SecurityQue.setText("Security Question");

        showPassword.setText("Show Password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel2))
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(R_ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showPassword)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(R_Password)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(R_Username, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addComponent(R_Email)
                                .addComponent(R_Security)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SecurityQue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SecurityQue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(R_Security, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPassword)
                .addGap(18, 18, 18)
                .addComponent(R_ResetBtn)
                .addGap(90, 90, 90))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton1)
                .addGap(174, 174, 174)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void R_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_EmailActionPerformed

    private void R_ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_ResetBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_ResetBtnActionPerformed

    private void R_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R_UsernameActionPerformed

    private void R_UsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_UsernameFocusGained
        if (R_Username.getText().equals("Username")) {
            R_Username.setText("");
        }
    }//GEN-LAST:event_R_UsernameFocusGained

    private void R_UsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_UsernameFocusLost
        if (R_Username.getText().isEmpty()) {
            R_Username.setText("Username");
        }
    }//GEN-LAST:event_R_UsernameFocusLost

    private void R_EmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_EmailFocusGained
        if (R_Email.getText().equals("Email")) {
            R_Email.setText("");
        }
    }//GEN-LAST:event_R_EmailFocusGained

    private void R_EmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_EmailFocusLost
        if (R_Email.getText().isEmpty()) {
            R_Email.setText("Email");
        }
        // Fetch and display security question
        String username = R_Username.getText();
        String email = R_Email.getText();
        dao.Forgot forgotDao = new dao.Forgot();
        String question = forgotDao.getSecurityQuestion(username, email);
        if (question != null) {
            SecurityQue.setText(question);
        } else {
            SecurityQue.setText("No security question found.");
        }
    }//GEN-LAST:event_R_EmailFocusLost

    private void R_SecurityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_SecurityFocusGained
        if (String.valueOf(R_Security.getPassword()).equals("Answer")) {
            R_Security.setText("");
            R_Security.setEchoChar('*');
        }
    }//GEN-LAST:event_R_SecurityFocusGained

    private void R_SecurityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_SecurityFocusLost
        if (String.valueOf(R_Security.getPassword()).isEmpty()) {
            R_Security.setText("Answer");
            R_Security.setEchoChar((char)0);
        }
    }//GEN-LAST:event_R_SecurityFocusLost

    private void R_PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_PasswordFocusGained
        if (String.valueOf(R_Password.getPassword()).equals("Password")) {
            R_Password.setText("");
            R_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_R_PasswordFocusGained

    private void R_PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_R_PasswordFocusLost
        if (String.valueOf(R_Password.getPassword()).isEmpty()) {
            R_Password.setText("Password");
            R_Password.setEchoChar((char)0);
        }
    }//GEN-LAST:event_R_PasswordFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        LoginController logincontroller = new LoginController(login);
        logincontroller.open();
        login.setVisible(true);
        login.setLocationRelativeTo(null); //bicha ma basne ho yeleeeeeee
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        // TODO add your handling code here:

        if(showPassword.isSelected()){
            R_Password.setEchoChar((char)0);
        }
        else{
            R_Password.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField R_Email;
    private javax.swing.JPasswordField R_Password;
    private javax.swing.JButton R_ResetBtn;
    private javax.swing.JPasswordField R_Security;
    private javax.swing.JTextField R_Username;
    private javax.swing.JLabel SecurityQue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables
    public javax.swing.JButton R_ResetBtn() {
        return R_ResetBtn;
    }
    public javax.swing.JPasswordField R_password_field() {
        return R_Password;
    }
    public javax.swing.JTextField R_username_field() {
        return R_Username;
    }
        public javax.swing.JPasswordField R_Security_field() {
        return R_Security;
    }
        public javax.swing.JTextField R_email_field() {
        return R_Email;
    }       
    public void ResetPasswordListener(ActionListener listener) {
        R_ResetBtn.addActionListener(listener);
    }  
    // public void addActionListener(ActionListener e) {
    //     R_ResetBtn.addActionListener(e);
    // }
    public String getUsername() {
        return R_Username.getText();
    }

    public String getEmail() {
        return R_Email.getText();
    }

    public String getSecurityAnswer() {
        return new String(R_Security.getPassword());
    }

    public String getNewPassword() {
        return new String(R_Password.getPassword());
    }
    public javax.swing.JLabel getSecurityQuestionLabel() {
        return SecurityQue;
    }
    public String getSecurityQuestion() {
        return SecurityQue.getText();
    }
}


